version: '3'

volumes:
    sock:

services:
    nginx:
        image: nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static:/static
            - sock:/sock
        ports:
            - "80:80"

    app:
        command: gunicorn --bind=unix:/sock/app.sock --workers=4 wsgi
        restart: always
        image: recurser
        volumes:
            - ./:/usr/src/app
            - sock:/sock/
